### ISSUE TITLE
TypeError: __str__ returned non-string (type NoneType)

### ISSUE THREAD

**Issue by Kevin66Z0** [vim-vdebug/vdebug#457] opened 2020-04-29 10:00 UTC
[vdebug.debug.log.save.zip](https://github.com/vim-vdebug/vdebug/files/4550982/vdebug.debug.log.save.zip)

- [ERROR] {Wed 29 2020 17:48:03} An error occured: <class 'TypeError'>
Traceback (most recent call last):
  File "/Users/zhulin/.vim/bundle/vdebug/python3/vdebug/event.py", line 771, in dispatch_event
    Dispatcher.events[name](self.__session_handler).run(*args)
  File "/Users/zhulin/.vim/bundle/vdebug/python3/vdebug/event.py", line 277, in run
    status_str = str(status)
TypeError: __str__ returned non-string (type NoneType)

Hi, my vdebug work well in php-cli, but with php-fpm always throw the error in end.

I set debug_file_level=2 and upload the log file.

**Comment by alfredbez** [comment] 2020-05-14 07:46
This is possibly a duplicate of #434

**Closed** 2020-08-18 16:00 UTC
