### ISSUE TITLE
ElementTree parse error in watch window

### ISSUE THREAD

**Issue by rapliandras** [vim-vdebug/vdebug#336] opened 2018-03-20 10:00 UTC
In the watch window I navigate to an array and want to unfold to view its elements (hit enter), yet I'm getting a nice parse error. 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/arapli/.vim/bundle/vdebug/pythonx/vdebug/debugger_interface.py", line 81, in handle_return_keypress
    return self.event_dispatcher.by_position(self.session_handler)
  File "/home/arapli/.vim/bundle/vdebug/pythonx/vdebug/event.py", line 543, in by_position
    return event.run()
  File "/home/arapli/.vim/bundle/vdebug/pythonx/vdebug/event.py", line 150, in run
    output = rend.render(pointer_index - 1)
  File "/home/arapli/.vim/bundle/vdebug/pythonx/vdebug/ui/vimui.py", line 736, in render
    properties = self.response.get_context()
  File "/home/arapli/.vim/bundle/vdebug/pythonx/vdebug/dbgp.py", line 132, in get_context
    for c in list(self.as_xml()):
  File "/home/arapli/.vim/bundle/vdebug/pythonx/vdebug/dbgp.py", line 75, in as_xml
    self.xml = ET.fromstring(self.response)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1333, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: reference to invalid character number: line 2, column 835
```
I have upgraded lxml to 4.2 via pip3.

Thanks for any advice.

**Comment by BlackIkeEagle** [comment] 2018-03-20 14:13
@rapliandras there might be a need for more information. from your traceback I could assume you are on Ubuntu, but if you could provide steps to reproduce the issue that would be great

**Comment by BlackIkeEagle** [comment] 2018-04-02 15:49
@rapliandras I can't reproduce this issue on ubuntu 16.04

**Comment by BlackIkeEagle** [comment] 2018-04-09 06:52
Closing because no further response

**Closed by BlackIkeEagle** 2018-04-09 06:52 UTC
